"""Regenerate results/tables/ from results/runs/ (§12.6).

Two rules this enforces, and they are the whole point of the file:

1. **A run made against a dirty git tree is refused.** An untracked local edit must not be
   able to change a published number silently.
2. **Every generated table carries the run_id it came from**, as a LaTeX comment and in the
   caption, so any figure in the paper can be traced back to the code and environment that
   produced it.

Nothing here computes a statistic. It formats what a runner already measured.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fcesreg.runs import RESULTS_ROOT, load_run

TABLES_ROOT = Path("results/tables")


class DirtyRun(RuntimeError):
    """Refusing to build a table from a run made against an uncommitted tree."""


def latest_run(script: str, root: Path = RESULTS_ROOT) -> str:
    """Most recent run id for a script. Run ids sort chronologically by construction."""
    candidates = sorted(d.name for d in root.iterdir() if d.name.startswith(f"{script}-"))
    if not candidates:
        raise FileNotFoundError(f"no runs found for {script} under {root}")
    return candidates[-1]


def _require_clean(run: dict) -> None:
    if run["env"].get("git_dirty"):
        raise DirtyRun(
            f"run {run['run_id']} was made against a dirty git tree "
            f"(sha {run['env'].get('git_short_sha')}). Commit the tree and re-run it. "
            "A number that cannot be traced to a commit does not go in the paper."
        )


def _esc(s: str) -> str:
    return str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def _wrap(body: str, caption: str, label: str, run_id: str, spec: str) -> str:
    return (
        f"% generated by make_tables.py from run {run_id}\n"
        "% do not edit — regenerate with `make tables`\n"
        "\\begin{table}[t]\n\\centering\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"\\begin{{tabular}}{{{spec}}}\n\\hline\n"
        f"{body}"
        "\\hline\n\\end{tabular}\n\\end{table}\n"
    )


def table_corpus_a(run: dict) -> str:
    m = run["metrics"]["corpus_a_abtbuy"]
    rows = [
        "Partition & Pairs & Positive & Positive rate \\\\\n\\hline\n",
    ]
    for split in ("train", "valid", "test"):
        s = m["splits"][split]
        rows.append(
            f"{split} & {s['n_pairs']:,} & {s['n_positive']:,} & "
            f"{100 * s['positive_rate']:.1f}\\% \\\\\n"
        )
    rows.append("\\hline\n")
    rows.append(
        f"total & {m['n_pairs']:,} & "
        f"{sum(s['n_positive'] for s in m['splits'].values()):,} & "
        f"{100 * m['positive_rate_overall']:.1f}\\% \\\\\n"
    )
    caption = (
        f"Corpus A (Abt-Buy): {m['n_records']:,} records "
        f"({m['n_records_table_a']:,} + {m['n_records_table_b']:,}) and the supplied "
        f"labelled pairs, used as given."
    )
    return _wrap("".join(rows), caption, "tab:corpus_a", run["run_id"], "lrrr")


def table_corpus_b(run: dict) -> str:
    m = run["metrics"]["corpus_b_contractsfinder"]
    adopted = m["adopted_division_set"]
    rows = ["Division set & Records & Dev & Test & Classes $\\geq$50 & Coverage \\\\\n\\hline\n"]
    for name, d in m["division_sets"].items():
        lvl = d["levels"]["class"]
        mark = " (adopted)" if name == adopted else ""
        rows.append(
            f"{len(d['divisions'])} divisions{mark} & {d['n_records']:,} & "
            f"{d['n_dev']:,} & {d['n_test']:,} & {lvl['n_labels_supported']} & "
            f"{100 * lvl['coverage_of_dev']:.1f}\\% \\\\\n"
        )
    caption = (
        f"Corpus B (Contracts Finder): corpus size and CPV class support with and "
        f"without divisions 39 and 48. Temporal split at {m['split']['cutoff']}."
    )
    return _wrap("".join(rows), caption, "tab:corpus_b", run["run_id"], "lrrrrr")


def table_discard(run: dict) -> str:
    d = run["metrics"]["corpus_b_contractsfinder"]["discard"]
    rows = ["Year & In & Out of scope & Short & Desc = title & Boilerplate & Out \\\\\n\\hline\n"]
    for year in sorted(d["per_year"]):
        r = d["per_year"][year]
        rows.append(
            f"{year} & {r['total_in']:,} & {r['dropped_out_of_scope']:,} & "
            f"{r['dropped_short']:,} & {r['dropped_desc_equals_title']:,} & "
            f"{r['dropped_boilerplate']:,} & {r['total_out']:,} \\\\\n"
        )
    c = d["combined"]
    rows.append("\\hline\n")
    rows.append(
        f"total & {c['total_in']:,} & {c['dropped_out_of_scope']:,} & "
        f"{c['dropped_short']:,} & {c['dropped_desc_equals_title']:,} & "
        f"{c['dropped_boilerplate']:,} & {c['total_out']:,} \\\\\n"
    )
    caption = (
        "Records discarded by each rule, applied in order so that every input row is "
        "attributed to the first rule it fails."
    )
    return _wrap("".join(rows), caption, "tab:discard", run["run_id"], "lrrrrrr")


def table_leaf_sparsity(run: dict) -> str:
    m = run["metrics"]["corpus_b_contractsfinder"]
    rows = ["Division set & Records & Distinct leaves & $\\geq$20 & $\\geq$50 & Singletons \\\\\n\\hline\n"]
    for name, d in m["division_sets"].items():
        s = d["leaf_sparsity"]
        mark = " (adopted)" if name == m["adopted_division_set"] else ""
        rows.append(
            f"{len(d['divisions'])} divisions{mark} & {s['n_records']:,} & "
            f"{s['n_distinct_leaves']:,} & {s['n_leaves_ge_20']:,} & "
            f"{s['n_leaves_ge_50']:,} & {s['n_singleton_leaves']:,} \\\\\n"
        )
    caption = (
        "Eight-digit leaf sparsity, the measurement behind not evaluating that level. "
        "Four years of data leave it as sparse as one."
    )
    return _wrap("".join(rows), caption, "tab:leaf_sparsity", run["run_id"], "lrrrrr")


def table_label_support(run: dict) -> str:
    """Imbalance and coverage at both taxonomy levels.

    The paper's Category Assignment section distinguishes the two levels: division is
    moderately skewed and fully covered, class is long-tailed and covered only in part.
    Both statements are numbers here, and the uncovered share is the fraction routed to
    review rather than discarded.
    """
    m = run["metrics"]["corpus_b_contractsfinder"]
    d = m["division_sets"][m["adopted_division_set"]]
    rows = [
        "Level & Labels & Supported & Smallest & Largest & Imbalance & Coverage \\\\\n\\hline\n"
    ]
    for level in ("division", "class"):
        lv = d["levels"][level]
        rows.append(
            f"{level} & {lv['n_labels_observed']} & {lv['n_labels_supported']} & "
            f"{lv['smallest_label_n']:,} & {lv['largest_label_n']:,} & "
            f"{lv['imbalance_ratio']:.1f}:1 & "
            f"{100 * lv['coverage_of_dev']:.1f}\\% \\\\\n"
        )
    lv = d["levels"]["class"]
    caption = (
        f"Label support on the adopted {len(d['divisions'])}-division set. Class-level "
        f"evaluation is restricted to labels with at least {lv['min_examples']} training "
        f"examples; the {100 * lv['uncovered_share_of_dev']:.1f}\\% of records outside "
        f"that set are routed to review, not discarded."
    )
    return _wrap("".join(rows), caption, "tab:label_support", run["run_id"], "lrrrrrr")


def table_division_choice(run: dict) -> str:
    """The measured basis for excluding divisions 39 and 48."""
    m = run["metrics"]["corpus_b_contractsfinder"]
    excl = m["excluded_divisions"]
    names = {"39": "Furniture", "48": "Software packages"}
    rows = ["Division & Contents & Records & Share of candidate corpus \\\\\n\\hline\n"]
    for code in sorted(excl):
        e = excl[code]
        rows.append(
            f"{code} & {names.get(code, '')} & {e['n_records']:,} & "
            f"{100 * e['share_of_widest_set']:.1f}\\% \\\\\n"
        )
    rows.append("\\hline\n")
    total = sum(e["n_records"] for e in excl.values())
    total_share = sum(e["share_of_widest_set"] for e in excl.values())
    rows.append(f"combined & & {total:,} & {100 * total_share:.1f}\\% \\\\\n")
    caption = (
        "Divisions excluded from the adopted set, and what each contributed to the "
        "candidate corpus. Neither describes a serviceable physical item bearing an "
        "asset tag."
    )
    return _wrap("".join(rows), caption, "tab:division_choice", run["run_id"], "llrr")


BUILDERS = {
    "run_profile": {
        "T1_corpus_a.tex": table_corpus_a,
        "T1_corpus_b.tex": table_corpus_b,
        "T1_discard.tex": table_discard,
        "T1_leaf_sparsity.tex": table_leaf_sparsity,
        "T1_label_support.tex": table_label_support,
        "T1_division_choice.tex": table_division_choice,
    },
}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--runs", type=Path, default=RESULTS_ROOT)
    p.add_argument("--out", type=Path, default=TABLES_ROOT)
    p.add_argument(
        "--allow-dirty",
        action="store_true",
        help="build anyway; the resulting numbers are not reproducible and must not ship",
    )
    args = p.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)

    built, skipped = 0, []
    for script, tables in BUILDERS.items():
        try:
            run = load_run(latest_run(script, args.runs), root=args.runs)
        except FileNotFoundError:
            skipped.append(f"{script}: no run yet")
            continue

        try:
            _require_clean(run)
        except DirtyRun as e:
            if not args.allow_dirty:
                print(f"\nREFUSED: {e}\n", file=sys.stderr)
                return 2
            print(f"WARNING: {e}", file=sys.stderr)

        for filename, builder in tables.items():
            (args.out / filename).write_text(builder(run), encoding="utf-8")
            print(f"  {args.out / filename}  <- {run['run_id']}")
            built += 1

    for s in skipped:
        print(f"  skipped {s}", file=sys.stderr)
    print(f"built {built} tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
