"""Regenerate results/tables/ from results/runs/ (§12.6).

Two rules this enforces, and they are the whole point of the file:

1. **A run made against a dirty git tree is refused.** An untracked local edit must not be
   able to change a published number silently.
2. **Every generated table carries the run_id it came from**, as a LaTeX comment and in the
   caption, so any figure in the paper can be traced back to the code and environment that
   produced it.

Nothing here computes a statistic. It formats what a runner already measured.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from fcesreg.degrade import ERROR_CLASSES
from fcesreg.paths import results_path
from fcesreg.runs import RESULTS_ROOT, load_run

TABLES_ROOT = results_path("tables")


class DirtyRun(RuntimeError):
    """Refusing to build a table from a run made against an uncommitted tree."""


def latest_run(script: str, root: Path = RESULTS_ROOT) -> str:
    """Most recent run id for a script. Run ids sort chronologically by construction."""
    candidates = sorted(d.name for d in root.iterdir() if d.name.startswith(f"{script}-"))
    if not candidates:
        raise FileNotFoundError(f"no runs found for {script} under {root}")
    return candidates[-1]


def _require_clean(run: dict) -> None:
    if run["env"].get("git_dirty"):
        raise DirtyRun(
            f"run {run['run_id']} was made against a dirty git tree "
            f"(sha {run['env'].get('git_short_sha')}). Commit the tree and re-run it. "
            "A number that cannot be traced to a commit does not go in the paper."
        )


def _esc(s: str) -> str:
    return str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def _wrap(
    body: str, caption: str, label: str, run_id: str, spec: str,
    compact: bool = False, wide: bool = False,
) -> str:
    """``compact=True`` scopes ``\\footnotesize`` and a tighter ``\\tabcolsep`` to just this
    table's ``tabular`` (braced, not ``\\resizebox`` -- scaling a table changes its font size
    relative to the body rather than fixing the actual overflow). Use it where a table's own
    column count/width genuinely needs it, not as a blanket default.

    ``wide=True`` uses ``table*`` (spans both IEEEtran columns) instead of ``table`` -- for a
    table whose column count/content cannot fit one column's width at any reasonable font
    size, not a default either.

    Float placement is ``[tb]`` (top or bottom of a column/page), not ``[t]`` alone: with six
    tables and four of them in eighty lines of Results, ``[t]``-only let LaTeX place at most
    two per page before deferring the rest, dragging body text forward and leaving whitespace
    behind it (supervisor diagnosis, 2026-08-26) -- a float-placement problem, not a length
    one, and cutting text does not fix it.
    """
    pre = "{\\footnotesize\\setlength{\\tabcolsep}{4pt}\n" if compact else ""
    post = "}\n" if compact else ""
    env = "table*" if wide else "table"
    return (
        f"% generated by make_tables.py from run {run_id}\n"
        "% do not edit — regenerate with `make tables`\n"
        f"\\begin{{{env}}}[tb]\n\\centering\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"{pre}"
        f"\\begin{{tabular}}{{{spec}}}\n\\hline\n"
        f"{body}"
        "\\hline\n\\end{tabular}\n"
        f"{post}"
        f"\\end{{{env}}}\n"
    )


def table_corpus(run: dict) -> str:
    """Both corpora's size and split, merged into one exhibit (supervisor ruling: five
    tables not eleven). Corpus A's unit is a labelled pair; Corpus B's is a record, split
    by division set rather than train/valid/test since the adopted set is the point being
    shown. The two blocks share columns loosely (n, a held-out count, a rate) rather than
    exactly, documented in the caption rather than forced into an artificial match.
    """
    a = run["metrics"]["corpus_a_abtbuy"]
    b = run["metrics"]["corpus_b_contractsfinder"]
    adopted = b["adopted_division_set"]

    rows = ["Corpus & Unit & n & Held out & Rate \\\\\n\\hline\n"]
    for split in ("train", "valid", "test"):
        s = a["splits"][split]
        rows.append(
            f"A: {split} & pairs & {s['n_pairs']:,} & --- & "
            f"{100 * s['positive_rate']:.1f}\\% positive \\\\\n"
        )
    rows.append(
        f"A: total & pairs & {a['n_pairs']:,} & --- & "
        f"{100 * a['positive_rate_overall']:.1f}\\% positive \\\\\n"
    )
    rows.append("\\hline\n")
    for name, d in b["division_sets"].items():
        lvl = d["levels"]["class"]
        mark = " (adopted)" if name == adopted else ""
        rows.append(
            f"B: {len(d['divisions'])} div.{mark} & records & {d['n_records']:,} & "
            f"{d['n_test']:,} test & {100 * lvl['coverage_of_dev']:.1f}\\% cov. \\\\\n"
        )
    caption = (
        f"Corpus A (Abt-Buy): {a['n_records']:,} records "
        f"({a['n_records_table_a']:,} + {a['n_records_table_b']:,}), supplied splits. "
        f"Corpus B (Contracts Finder): records by retained division set, temporal split at "
        f"{b['split']['cutoff']}. Rate: positive share of pairs (A); class-level coverage "
        f"of the development partition at $\\geq$50 training examples (B)."
    )
    return _wrap("".join(rows), caption, "tab:corpus", run["run_id"], "llrrr")


def table_discard(run: dict) -> str:
    d = run["metrics"]["corpus_b_contractsfinder"]["discard"]
    rows = ["Year & In & Out of scope & Short & Desc = title & Boilerplate & Out \\\\\n\\hline\n"]
    for year in sorted(d["per_year"]):
        r = d["per_year"][year]
        rows.append(
            f"{year} & {r['total_in']:,} & {r['dropped_out_of_scope']:,} & "
            f"{r['dropped_short']:,} & {r['dropped_desc_equals_title']:,} & "
            f"{r['dropped_boilerplate']:,} & {r['total_out']:,} \\\\\n"
        )
    c = d["combined"]
    rows.append("\\hline\n")
    rows.append(
        f"total & {c['total_in']:,} & {c['dropped_out_of_scope']:,} & "
        f"{c['dropped_short']:,} & {c['dropped_desc_equals_title']:,} & "
        f"{c['dropped_boilerplate']:,} & {c['total_out']:,} \\\\\n"
    )
    caption = (
        "Records discarded by each rule, applied in order so that every input row is "
        "attributed to the first rule it fails."
    )
    return _wrap("".join(rows), caption, "tab:discard", run["run_id"], "lrrrrrr")


def table_leaf_sparsity(run: dict) -> str:
    m = run["metrics"]["corpus_b_contractsfinder"]
    rows = ["Division set & Records & Distinct leaves & $\\geq$20 & $\\geq$50 & Singletons \\\\\n\\hline\n"]
    for name, d in m["division_sets"].items():
        s = d["leaf_sparsity"]
        mark = " (adopted)" if name == m["adopted_division_set"] else ""
        rows.append(
            f"{len(d['divisions'])} divisions{mark} & {s['n_records']:,} & "
            f"{s['n_distinct_leaves']:,} & {s['n_leaves_ge_20']:,} & "
            f"{s['n_leaves_ge_50']:,} & {s['n_singleton_leaves']:,} \\\\\n"
        )
    caption = (
        "Eight-digit leaf sparsity, the measurement behind not evaluating that level. "
        "Four years of data leave it as sparse as one."
    )
    return _wrap("".join(rows), caption, "tab:leaf_sparsity", run["run_id"], "lrrrrr")


def table_label_support(run: dict) -> str:
    """Imbalance and coverage at both taxonomy levels.

    The paper's Category Assignment section distinguishes the two levels: division is
    moderately skewed and fully covered, class is long-tailed and covered only in part.
    Both statements are numbers here, and the uncovered share is the fraction routed to
    review rather than discarded.
    """
    m = run["metrics"]["corpus_b_contractsfinder"]
    d = m["division_sets"][m["adopted_division_set"]]
    rows = [
        "Level & Labels & Supported & Smallest & Largest & Imbalance & Coverage \\\\\n\\hline\n"
    ]
    for level in ("division", "class"):
        lv = d["levels"][level]
        rows.append(
            f"{level} & {lv['n_labels_observed']} & {lv['n_labels_supported']} & "
            f"{lv['smallest_label_n']:,} & {lv['largest_label_n']:,} & "
            f"{lv['imbalance_ratio']:.1f}:1 & "
            f"{100 * lv['coverage_of_dev']:.1f}\\% \\\\\n"
        )
    lv = d["levels"]["class"]
    caption = (
        f"Label support on the adopted {len(d['divisions'])}-division set. Class-level "
        f"evaluation is restricted to labels with at least {lv['min_examples']} training "
        f"examples; the {100 * lv['uncovered_share_of_dev']:.1f}\\% of records outside "
        f"that set are routed to review, not discarded."
    )
    return _wrap("".join(rows), caption, "tab:label_support", run["run_id"], "lrrrrrr")


def table_division_choice(run: dict) -> str:
    """The measured basis for excluding divisions 39 and 48."""
    m = run["metrics"]["corpus_b_contractsfinder"]
    excl = m["excluded_divisions"]
    names = {"39": "Furniture", "48": "Software packages"}
    rows = ["Division & Contents & Records & Share of candidate corpus \\\\\n\\hline\n"]
    for code in sorted(excl):
        e = excl[code]
        rows.append(
            f"{code} & {names.get(code, '')} & {e['n_records']:,} & "
            f"{100 * e['share_of_widest_set']:.1f}\\% \\\\\n"
        )
    rows.append("\\hline\n")
    total = sum(e["n_records"] for e in excl.values())
    total_share = sum(e["share_of_widest_set"] for e in excl.values())
    rows.append(f"combined & & {total:,} & {100 * total_share:.1f}\\% \\\\\n")
    caption = (
        "Divisions excluded from the adopted set, and what each contributed to the "
        "candidate corpus. Neither describes a serviceable physical item bearing an "
        "asset tag."
    )
    return _wrap("".join(rows), caption, "tab:division_choice", run["run_id"], "llrr")


def table_blocking(run: dict) -> str:
    """Pair completeness and reduction ratio, per scheme and per corpus.

    Deliberately not averaged across corpora: ``buyer_id`` exists on Corpus B and not on
    Corpus A, and which schemes are available where is part of what the result says.
    Pair completeness on Corpus B is left blank rather than estimated — that corpus has no
    labelled duplicate pairs until the degradation model supplies them.
    """
    rows = ["Corpus & Scheme & PC & RR & Candidates & Largest block \\\\\n\\hline\n"]
    for key, m in run["metrics"].items():
        corpus, _, mode = key.partition("::")
        short = "A (Abt-Buy)" if "abtbuy" in corpus else "B (Contracts Finder)"
        for scheme, e in m["per_scheme"].items():
            name = f"{scheme} [{mode}]" if scheme == "sorted_ngrams" else scheme
            pc = e.get("pair_completeness")
            rr = e.get("reduction_ratio")
            rows.append(
                f"{short} & {_esc(name)} & "
                f"{f'{pc:.3f}' if pc is not None else '---'} & "
                f"{f'{rr:.4f}' if rr is not None else '---'} & "
                f"{e['n_candidates']:,} & {e['largest_block']:,} \\\\\n"
            )
    caption = (
        "Blocking by scheme and corpus. PC is pair completeness, the recall ceiling "
        "everything downstream inherits; RR is reduction ratio. The buyer scheme is "
        "unavailable on Corpus A, which has no publishing authority. PC is unmeasured on "
        "Corpus B, which carries no labelled duplicate pairs."
    )
    return _wrap("".join(rows), caption, "tab:blocking", run["run_id"], "llrrrr")


def table_abtbuy(run: dict) -> str:
    """T4_abtbuy: RQ1, the matcher comparison on Corpus A, including the cascade.

    ``run["metrics"]["free_matchers"]`` is the full factorial (matcher x severity x seed);
    rows here are averaged over seeds, one row per (matcher, severity) that actually admits
    a threshold. A (matcher, severity) with no threshold contributes nothing to the table
    body -- it is a finding stated once in the caption, not a row repeated per combination,
    since a table where fourteen of fifteen base-matcher rows read "no threshold" spends
    its rows saying the same thing fourteen times. Cascade rows come from
    ``run["metrics"]["cascade"]`` separately, since it runs a single seed at three
    severities rather than the free matchers' full factorial, and its precision splits into
    an auto-accepted figure and a combined one -- reported as two columns rather than
    collapsed into one, since collapsing would attribute the adjudicator's error rate to a
    threshold that never saw those pairs.
    """
    import pandas as pd

    rows = ["Matcher & Sev. & P & R & F1 \\\\\n\\hline\n"]
    free = pd.DataFrame(run["metrics"]["free_matchers"])
    for matcher in free["matcher"].unique():
        block = free[free["matcher"] == matcher]
        for severity, g in block.groupby("severity"):
            # threshold is None where no score met the Wilson-bound precision target on
            # dev -- nothing was accepted, which is a different statement from "accepted
            # everything and scored 0". Omitted from the table rather than shown as a
            # measured 0.000; the omission itself is reported in the caption below.
            if g["threshold"].isna().all():
                continue
            rows.append(
                f"{_esc(matcher)} & {severity} & {g['precision'].mean():.3f} & "
                f"{g['recall'].mean():.3f} & {g['f1'].mean():.3f} \\\\\n"
            )
    rows.append("\\hline\n")
    for row in run["metrics"]["cascade"]:
        auto = row.get("precision_auto_accepted")
        auto_s = "---" if auto is None else f"{auto:.3f}"
        rows.append(
            f"cascade & {row['severity']} & {row['precision']:.3f} ({auto_s} auto) & "
            f"{row['recall']:.3f} & {row['f1']:.3f} \\\\\n"
        )
    caption = (
        "Corpus A matcher comparison, precision/recall/F1 averaged over seeds (free "
        "matchers) or single-seed with every band pair adjudicated (cascade). Cascade "
        "precision is combined output; auto is the auto-accepted portion alone. Severity "
        "0.5 is an 800-pair stratified subsample, not the full band. Omitted rows have no "
        "threshold reaching the 0.95 precision floor on dev, not a measured zero."
    )
    return _wrap("".join(rows), caption, "tab:abtbuy", run["run_id"], "lcccc")


def table_classification(run: dict) -> str:
    """RQ2: both classical conditions at both levels, and the level's routed-to-review
    share broken out by cause.

    Class level restricts to labels meeting the training-example floor AND records
    genuinely carrying a class-level code -- a division-only code (``cpv.labelled_at``)
    is not a class and scoring it would credit the model for predicting that a buyer left
    the record unclassified. The two exclusions are reported apart because they are
    different failures: one is a rare category, the other is a category that does not
    exist for that record.
    """
    order = ["division", "class"]
    condition_label = {"tfidf_svm": "TF-IDF+SVM", "embedding_logreg": "Embedding+LogReg"}
    rows = ["Level & Condition & Macro F1 & Weighted F1 & Acc. & Rev. \\% \\\\\n\\hline\n"]
    for level in order:
        if level not in run["metrics"]["levels"]:
            continue
        result = run["metrics"]["levels"][level]
        routed = result["test_routed_to_review"]
        for name in ("tfidf_svm", "embedding_logreg"):
            if name not in result["conditions"]:
                continue
            c = result["conditions"][name]
            rows.append(
                f"{level.capitalize()} & {_esc(condition_label.get(name, name))} & "
                f"{c['macro_f1']:.3f} & {c['weighted_f1']:.3f} & {c['accuracy']:.3f} & "
                f"{100 * routed:.1f}\\% \\\\\n"
            )
    caption = (
        "Category assignment, both classical conditions. Class level restricts to "
        "labels meeting the training-example floor and records carrying a genuine "
        "class-level code; routed-to-review figures are broken out by cause in the text."
    )
    return _wrap(
        "".join(rows), caption, "tab:classification", run["run_id"], "llrrrr", compact=True
    )


def table_costs(run: dict) -> str:
    """T8_cost: cascade throughput and notional cost per 1,000 pairs, per severity.

    **Not yet registered in BUILDERS.** ``run_costs.py`` deduplicates the live ledger by
    ``prompt_sha256`` so this is already immune to replay inflation, but the band fraction
    and ``n_pairs`` it reads come from a ``run_dedup --cascade`` record that is not yet a
    finished 1,209/1,209 -- wire this in once that run lands, so the table reports the
    completed cascade rather than a partial day's.
    """
    m = run["metrics"]
    latency = "n/a" if m["mean_latency_ms"] is None else f"{m['mean_latency_ms']:.0f}"
    rows = [
        "Sev. & Band & Adjudicated/Pairs & USD/1000 adj. & Tokens/1000 adj. \\\\\n\\hline\n"
    ]
    for row in m["band"]:
        rows.append(
            f"{row['severity']} & {100 * row['band_fraction']:.1f}\\% & "
            f"{row['n_adjudicated']}/{row['n_pairs']} & "
            f"{row['usd_per_1000']:.4f} & {row['tokens_per_1000']:.0f} \\\\\n"
        )
    caption = (
        f"Cascade cost, deduplicated by prompt across every day the sweep took: "
        f"{m['n_calls']} distinct adjudications, mean latency {latency}\\,ms over live "
        f"calls only, throughput "
        f"{m['throughput_per_day']['calls_per_day']:.0f}/day bound by "
        f"{_esc(m['throughput_per_day']['binding_limit'])}. \\$0.00 actual spend; USD is "
        "notional at the ledger's rate card."
    )
    return _wrap("".join(rows), caption, "tab:costs", run["run_id"], "lrrrr", compact=True)


def table_transfer(run: dict) -> str:
    """External Validation: the cap-sweep attribution, per corpus per cap per severity.

    A reader cannot recover a 1,209x candidate-volume cost from reduction ratios sitting
    near 1 on either side, so candidates is reported directly rather than RR alone. This
    table answers "what does rescaling the guard cost", not "does the matcher rank the same
    way" -- that comparison lives in T4_abtbuy's Corpus A panel and T3_blocking's Corpus B
    panel, unaffected by any of this.

    **At severity 0.0 only the two endpoint caps (500, shipped; none, fully rescaled) are
    shown** (page-budget cut, 2026-09-01) -- the only two the prose narrates ("at the shipped
    500-cap configuration... rescaling the cap recovers completeness"). The intermediate
    sweep points (2,000 and 10,000) are still in the run record for anyone regenerating this
    table to check; dropping them from the rendered table loses no cited number. Severity
    0.25's single rescaled-cap row is unaffected -- it was never swept at multiple caps.
    """
    shown_caps = {500, None}
    rows = ["Corpus & Sev. & Cap & PC & Candidates & Dropped \\\\\n\\hline\n"]
    for row in run["metrics"]["rows"]:
        if row["severity"] == 0.0 and row["cap"] not in shown_caps:
            continue
        short = "A (Abt-Buy)" if row["corpus"] == "corpus_a" else "B (Contracts Finder)"
        cap = "none" if row["cap"] is None else f"{row['cap']:,}"
        rows.append(
            f"{short} & {row['severity']} & {cap} & {row['pair_completeness']:.3f} & "
            f"{row['n_candidates']:,} & {row['blocks_dropped']:,} \\\\\n"
        )
    caption = (
        "Block-size cap, shipped (500) against fully rescaled (none), both corpora, at "
        "severity 0.0 (Corpus B positives byte-identical there); and the rescaled cap at "
        "severity 0.25, where the two corpora's blocking behaviour diverges. PC is pair "
        "completeness; candidates and blocks dropped are reported directly since reduction "
        "ratio alone does not convey the volume cost of rescaling the cap."
    )
    return _wrap("".join(rows), caption, "tab:transfer", run["run_id"], "lcccrr", compact=True)


_CLASS_LABEL = {
    "abbreviate": "Abbreviation",
    "charnoise": "Character noise",
    "case": "Casing",
    "whitespace": "Whitespace",
    "units": "Unit/voltage notation",
    "omit": "Field omission",
    "merge": "Field merging",
}

#: Where each class's construction is documented. Field merging is Mudgal et al.'s dirty-data
#: protocol (relocating an attribute into a free-text field); every other class is drawn from
#: the quality issues the Contracts Finder publisher documents plus a manual audit of the raw
#: data (degrade.py's own module docstring states this exactly; repeated here as the
#: citable source for the table rather than re-derived).
_CLASS_SOURCE = {
    "abbreviate": "CF audit",
    "charnoise": "CF audit",
    "case": "CF audit",
    "whitespace": "CF audit",
    "units": "CF audit",
    "omit": "CF audit",
    "merge": "Mudgal et al.~\\cite{mudgal2018}",
}


def _first_diff_window(before: str, after: str, context: int = 15) -> tuple[str, str]:
    """A short window around the first point ``before`` and ``after`` diverge -- a real
    record is a paragraph, not a table cell, so this formats a legible fragment of the
    run's own measured before/after rather than computing anything new."""
    n = min(len(before), len(after))
    i = 0
    while i < n and before[i] == after[i]:
        i += 1
    start = max(0, i - context)
    b_end = min(len(before), i + context)
    a_end = min(len(after), i + context)

    def _clean(s: str) -> str:
        return re.sub(r"\s+", " ", s.replace("\r", " ").replace("\n", " ")).strip()

    b = _clean(before[start:b_end])
    a = _clean(after[start:a_end])
    ellipsis = "\\ldots{}"
    prefix = ellipsis if start > 0 else ""
    b_suffix = ellipsis if b_end < len(before) else ""
    a_suffix = ellipsis if a_end < len(after) else ""
    return f"{prefix}{b}{b_suffix}", f"{prefix}{a}{a_suffix}"


def table_degradation(run: dict) -> str:
    """T-degradation: one real before/after example per error class, and its documented
    source (supervisor request, 2026-08-26; redesigned single-column 2026-08-27) -- the
    Degradation Model subsection named the seven classes and deferred their parameters to
    the code; this makes them reproducible from the paper directly.

    **The per-severity probability columns this table carried were dropped.** Every class
    shares the identical p(severity) value at every severity because ``run_dedup.py`` and
    ``run_transfer.py`` -- the runners that produced every other reported number -- construct
    ``DegradationConfig(severity)`` with no per-class multiplier override, so ``rate(class) =
    severity`` uniformly for all seven. Three identical columns were a sentence, not a table
    (supervisor finding, 2026-08-27): $p_s = s$ is now stated once, in the caption, and the
    reclaimed width lets the table run single-column (``table``, not ``table*``) rather than
    spanning both -- the example windows are correspondingly shorter (``context=8``, was 15)
    to fit it. The per-class multiplier mechanism itself still exists (used only by the
    isolated degradation-damage diagnostic) and is still not part of the reported sweeps.
    """
    rows = ["Class & Example (before $\\to$ after) & Source \\\\\n\\hline\n"]
    for cls in ERROR_CLASSES:
        c = run["metrics"]["classes"][cls]
        before, after = _first_diff_window(
            c["example"]["before"], c["example"]["after"], context=8
        )
        rows.append(
            f"{_CLASS_LABEL[cls]} & {_esc(before)} $\\to$ {_esc(after)} & "
            f"{_CLASS_SOURCE[cls]} \\\\\n"
        )
    caption = (
        "The seven degradation error classes: a real Contracts Finder record before/after "
        "that class alone (isolated via a per-class multiplier at severity 1.0, undiluted). "
        "Each fires with probability $p_s = s$ at swept severity $s$ -- the multiplier is "
        "1.0 for every class in every reported run, so $p_s$ does not vary by class."
    )
    return _wrap(
        "".join(rows), caption, "tab:degradation", run["run_id"], "p{1.6cm}p{5.0cm}p{1.6cm}",
        compact=True, wide=False,
    )


def table_cost_scale(costs_run: dict, dedup_run: dict) -> str:
    """T_cost_scale: the operational cost table extrapolated to illustrative register sizes
    (supervisor request, 2026-08-27) -- appendix-only, not registered in ``BUILDERS`` because
    it takes two run records rather than one and the main paper's page budget has no room
    for a sixth table regardless.

    **Extrapolation, stated as such.** ``run_costs`` measures the mean cost and token count
    of one adjudication, and ``run_dedup``'s cascade record measures the severity-0 review
    band as a fraction of candidate pairs (6.6%, the same figure F4 reports). Expected calls
    at size $N$ is $N \\times$ that fraction; tokens and
    USD scale from the measured per-call means. Nothing here is a new measurement: it is the
    same per-call rate multiplied by a hypothetical $N$, and the caption says so. Sizes
    1,000 / 10,000 / 50,000 are illustrative registers, not measured corpora.
    """
    band0 = next(r for r in dedup_run["metrics"]["cascade"] if r["severity"] == 0.0)
    band_fraction = band0["band_fraction"]
    usd_per_call = costs_run["metrics"]["usd_one_clean_run"] / costs_run["metrics"]["n_calls"]
    tokens_per_call = costs_run["metrics"]["mean_tokens_per_call"]

    rows = ["N (candidate pairs) & Expected LM calls & Tokens & Notional USD \\\\\n\\hline\n"]
    for n in (1000, 10000, 50000):
        calls = n * band_fraction
        rows.append(
            f"{n:,} & {calls:,.0f} & {calls * tokens_per_call:,.0f} & "
            f"{calls * usd_per_call:,.4f} \\\\\n"
        )
    caption = (
        f"Operational cost extrapolated from measured per-call figures ({tokens_per_call:.1f} "
        f"tokens/call, \\${usd_per_call:.6f}/call), scaled by "
        f"the severity-0 cascade review band ({100 * band_fraction:.1f}\\% of candidate pairs) "
        f"-- illustrative registers, not measured corpora."
    )
    return _wrap(
        "".join(rows), caption, "tab:cost-scale",
        f"{costs_run['run_id']}+{dedup_run['run_id']}", "rrrr",
        compact=True, wide=False,
    )


BUILDERS = {
    # T3_blocking dropped as a table (supervisor ruling: five tables not eleven); its
    # numbers that matter for prose are folded into T9_transfer or stated inline.
    "run_classify": {"T6_classification.tex": table_classification},
    "run_transfer_attribution": {"T9_transfer.tex": table_transfer},
    "run_costs": {"T8_cost.tex": table_costs},
    "run_dedup": {"T4_abtbuy.tex": table_abtbuy},
    "run_degradation_examples": {"T_degradation.tex": table_degradation},
    "run_profile": {
        # T1_corpus dropped as a table too (supervisor ruling, 2026-08-27): the only
        # descriptive-rather-than-interpretive table among six, in a document that could
        # only afford five. Its numbers are folded into the Corpus A/B prose in main.tex.
        # T1_discard, T1_leaf_sparsity, T1_label_support, T1_division_choice dropped as
        # tables (supervisor ruling): each is a single number or short list that reads
        # fine in a sentence. The builder functions stay, for anyone regenerating the
        # figure to check a prose number against.
    },
}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--runs", type=Path, default=RESULTS_ROOT)
    p.add_argument("--out", type=Path, default=TABLES_ROOT)
    p.add_argument(
        "--allow-dirty",
        action="store_true",
        help="build anyway; the resulting numbers are not reproducible and must not ship",
    )
    args = p.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)

    built, skipped = 0, []
    for script, tables in BUILDERS.items():
        try:
            run = load_run(latest_run(script, args.runs), root=args.runs)
        except FileNotFoundError:
            skipped.append(f"{script}: no run yet")
            continue

        try:
            _require_clean(run)
        except DirtyRun as e:
            if not args.allow_dirty:
                print(f"\nREFUSED: {e}\n", file=sys.stderr)
                return 2
            print(f"WARNING: {e}", file=sys.stderr)

        for filename, builder in tables.items():
            (args.out / filename).write_text(builder(run), encoding="utf-8")
            print(f"  {args.out / filename}  <- {run['run_id']}")
            built += 1

    for s in skipped:
        print(f"  skipped {s}", file=sys.stderr)
    print(f"built {built} tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
