"""Regenerate results/tables/ from results/runs/ (§12.6).

Two rules this enforces, and they are the whole point of the file:

1. **A run made against a dirty git tree is refused.** An untracked local edit must not be
   able to change a published number silently.
2. **Every generated table carries the run_id it came from**, as a LaTeX comment and in the
   caption, so any figure in the paper can be traced back to the code and environment that
   produced it.

Nothing here computes a statistic. It formats what a runner already measured.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fcesreg.paths import results_path
from fcesreg.runs import RESULTS_ROOT, load_run

TABLES_ROOT = results_path("tables")


class DirtyRun(RuntimeError):
    """Refusing to build a table from a run made against an uncommitted tree."""


def latest_run(script: str, root: Path = RESULTS_ROOT) -> str:
    """Most recent run id for a script. Run ids sort chronologically by construction."""
    candidates = sorted(d.name for d in root.iterdir() if d.name.startswith(f"{script}-"))
    if not candidates:
        raise FileNotFoundError(f"no runs found for {script} under {root}")
    return candidates[-1]


def _require_clean(run: dict) -> None:
    if run["env"].get("git_dirty"):
        raise DirtyRun(
            f"run {run['run_id']} was made against a dirty git tree "
            f"(sha {run['env'].get('git_short_sha')}). Commit the tree and re-run it. "
            "A number that cannot be traced to a commit does not go in the paper."
        )


def _esc(s: str) -> str:
    return str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def _wrap(body: str, caption: str, label: str, run_id: str, spec: str, compact: bool = False) -> str:
    """``compact=True`` scopes ``\\footnotesize`` and a tighter ``\\tabcolsep`` to just this
    table's ``tabular`` (braced, not ``\\resizebox`` -- scaling a table changes its font size
    relative to the body rather than fixing the actual overflow). Use it where a table's own
    column count/width genuinely needs it, not as a blanket default."""
    pre = "{\\footnotesize\\setlength{\\tabcolsep}{4pt}\n" if compact else ""
    post = "}\n" if compact else ""
    return (
        f"% generated by make_tables.py from run {run_id}\n"
        "% do not edit — regenerate with `make tables`\n"
        "\\begin{table}[t]\n\\centering\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"{pre}"
        f"\\begin{{tabular}}{{{spec}}}\n\\hline\n"
        f"{body}"
        "\\hline\n\\end{tabular}\n"
        f"{post}"
        "\\end{table}\n"
    )


def table_corpus(run: dict) -> str:
    """Both corpora's size and split, merged into one exhibit (supervisor ruling: five
    tables not eleven). Corpus A's unit is a labelled pair; Corpus B's is a record, split
    by division set rather than train/valid/test since the adopted set is the point being
    shown. The two blocks share columns loosely (n, a held-out count, a rate) rather than
    exactly, documented in the caption rather than forced into an artificial match.
    """
    a = run["metrics"]["corpus_a_abtbuy"]
    b = run["metrics"]["corpus_b_contractsfinder"]
    adopted = b["adopted_division_set"]

    rows = ["Corpus & Unit & n & Held out & Rate \\\\\n\\hline\n"]
    for split in ("train", "valid", "test"):
        s = a["splits"][split]
        rows.append(
            f"A: {split} & pairs & {s['n_pairs']:,} & --- & "
            f"{100 * s['positive_rate']:.1f}\\% positive \\\\\n"
        )
    rows.append(
        f"A: total & pairs & {a['n_pairs']:,} & --- & "
        f"{100 * a['positive_rate_overall']:.1f}\\% positive \\\\\n"
    )
    rows.append("\\hline\n")
    for name, d in b["division_sets"].items():
        lvl = d["levels"]["class"]
        mark = " (adopted)" if name == adopted else ""
        rows.append(
            f"B: {len(d['divisions'])} div.{mark} & records & {d['n_records']:,} & "
            f"{d['n_test']:,} test & {100 * lvl['coverage_of_dev']:.1f}\\% cov. \\\\\n"
        )
    caption = (
        f"Corpus A (Abt-Buy): {a['n_records']:,} records "
        f"({a['n_records_table_a']:,} + {a['n_records_table_b']:,}), supplied splits. "
        f"Corpus B (Contracts Finder): records by retained division set, temporal split at "
        f"{b['split']['cutoff']}. Rate: positive share of pairs (A); class-level coverage "
        f"of the development partition at $\\geq$50 training examples (B)."
    )
    return _wrap("".join(rows), caption, "tab:corpus", run["run_id"], "llrrr")


def table_discard(run: dict) -> str:
    d = run["metrics"]["corpus_b_contractsfinder"]["discard"]
    rows = ["Year & In & Out of scope & Short & Desc = title & Boilerplate & Out \\\\\n\\hline\n"]
    for year in sorted(d["per_year"]):
        r = d["per_year"][year]
        rows.append(
            f"{year} & {r['total_in']:,} & {r['dropped_out_of_scope']:,} & "
            f"{r['dropped_short']:,} & {r['dropped_desc_equals_title']:,} & "
            f"{r['dropped_boilerplate']:,} & {r['total_out']:,} \\\\\n"
        )
    c = d["combined"]
    rows.append("\\hline\n")
    rows.append(
        f"total & {c['total_in']:,} & {c['dropped_out_of_scope']:,} & "
        f"{c['dropped_short']:,} & {c['dropped_desc_equals_title']:,} & "
        f"{c['dropped_boilerplate']:,} & {c['total_out']:,} \\\\\n"
    )
    caption = (
        "Records discarded by each rule, applied in order so that every input row is "
        "attributed to the first rule it fails."
    )
    return _wrap("".join(rows), caption, "tab:discard", run["run_id"], "lrrrrrr")


def table_leaf_sparsity(run: dict) -> str:
    m = run["metrics"]["corpus_b_contractsfinder"]
    rows = ["Division set & Records & Distinct leaves & $\\geq$20 & $\\geq$50 & Singletons \\\\\n\\hline\n"]
    for name, d in m["division_sets"].items():
        s = d["leaf_sparsity"]
        mark = " (adopted)" if name == m["adopted_division_set"] else ""
        rows.append(
            f"{len(d['divisions'])} divisions{mark} & {s['n_records']:,} & "
            f"{s['n_distinct_leaves']:,} & {s['n_leaves_ge_20']:,} & "
            f"{s['n_leaves_ge_50']:,} & {s['n_singleton_leaves']:,} \\\\\n"
        )
    caption = (
        "Eight-digit leaf sparsity, the measurement behind not evaluating that level. "
        "Four years of data leave it as sparse as one."
    )
    return _wrap("".join(rows), caption, "tab:leaf_sparsity", run["run_id"], "lrrrrr")


def table_label_support(run: dict) -> str:
    """Imbalance and coverage at both taxonomy levels.

    The paper's Category Assignment section distinguishes the two levels: division is
    moderately skewed and fully covered, class is long-tailed and covered only in part.
    Both statements are numbers here, and the uncovered share is the fraction routed to
    review rather than discarded.
    """
    m = run["metrics"]["corpus_b_contractsfinder"]
    d = m["division_sets"][m["adopted_division_set"]]
    rows = [
        "Level & Labels & Supported & Smallest & Largest & Imbalance & Coverage \\\\\n\\hline\n"
    ]
    for level in ("division", "class"):
        lv = d["levels"][level]
        rows.append(
            f"{level} & {lv['n_labels_observed']} & {lv['n_labels_supported']} & "
            f"{lv['smallest_label_n']:,} & {lv['largest_label_n']:,} & "
            f"{lv['imbalance_ratio']:.1f}:1 & "
            f"{100 * lv['coverage_of_dev']:.1f}\\% \\\\\n"
        )
    lv = d["levels"]["class"]
    caption = (
        f"Label support on the adopted {len(d['divisions'])}-division set. Class-level "
        f"evaluation is restricted to labels with at least {lv['min_examples']} training "
        f"examples; the {100 * lv['uncovered_share_of_dev']:.1f}\\% of records outside "
        f"that set are routed to review, not discarded."
    )
    return _wrap("".join(rows), caption, "tab:label_support", run["run_id"], "lrrrrrr")


def table_division_choice(run: dict) -> str:
    """The measured basis for excluding divisions 39 and 48."""
    m = run["metrics"]["corpus_b_contractsfinder"]
    excl = m["excluded_divisions"]
    names = {"39": "Furniture", "48": "Software packages"}
    rows = ["Division & Contents & Records & Share of candidate corpus \\\\\n\\hline\n"]
    for code in sorted(excl):
        e = excl[code]
        rows.append(
            f"{code} & {names.get(code, '')} & {e['n_records']:,} & "
            f"{100 * e['share_of_widest_set']:.1f}\\% \\\\\n"
        )
    rows.append("\\hline\n")
    total = sum(e["n_records"] for e in excl.values())
    total_share = sum(e["share_of_widest_set"] for e in excl.values())
    rows.append(f"combined & & {total:,} & {100 * total_share:.1f}\\% \\\\\n")
    caption = (
        "Divisions excluded from the adopted set, and what each contributed to the "
        "candidate corpus. Neither describes a serviceable physical item bearing an "
        "asset tag."
    )
    return _wrap("".join(rows), caption, "tab:division_choice", run["run_id"], "llrr")


def table_blocking(run: dict) -> str:
    """Pair completeness and reduction ratio, per scheme and per corpus.

    Deliberately not averaged across corpora: ``buyer_id`` exists on Corpus B and not on
    Corpus A, and which schemes are available where is part of what the result says.
    Pair completeness on Corpus B is left blank rather than estimated — that corpus has no
    labelled duplicate pairs until the degradation model supplies them.
    """
    rows = ["Corpus & Scheme & PC & RR & Candidates & Largest block \\\\\n\\hline\n"]
    for key, m in run["metrics"].items():
        corpus, _, mode = key.partition("::")
        short = "A (Abt-Buy)" if "abtbuy" in corpus else "B (Contracts Finder)"
        for scheme, e in m["per_scheme"].items():
            name = f"{scheme} [{mode}]" if scheme == "sorted_ngrams" else scheme
            pc = e.get("pair_completeness")
            rr = e.get("reduction_ratio")
            rows.append(
                f"{short} & {_esc(name)} & "
                f"{f'{pc:.3f}' if pc is not None else '---'} & "
                f"{f'{rr:.4f}' if rr is not None else '---'} & "
                f"{e['n_candidates']:,} & {e['largest_block']:,} \\\\\n"
            )
    caption = (
        "Blocking by scheme and corpus. PC is pair completeness, the recall ceiling "
        "everything downstream inherits; RR is reduction ratio. The buyer scheme is "
        "unavailable on Corpus A, which has no publishing authority. PC is unmeasured on "
        "Corpus B, which carries no labelled duplicate pairs."
    )
    return _wrap("".join(rows), caption, "tab:blocking", run["run_id"], "llrrrr")


def table_abtbuy(run: dict) -> str:
    """T4_abtbuy: RQ1, the matcher comparison on Corpus A, including the cascade.

    ``run["metrics"]["free_matchers"]`` is the full factorial (matcher x severity x seed);
    rows here are averaged over seeds, one row per (matcher, severity) that actually admits
    a threshold. A (matcher, severity) with no threshold contributes nothing to the table
    body -- it is a finding stated once in the caption, not a row repeated per combination,
    since a table where fourteen of fifteen base-matcher rows read "no threshold" spends
    its rows saying the same thing fourteen times. Cascade rows come from
    ``run["metrics"]["cascade"]`` separately, since it runs a single seed at three
    severities rather than the free matchers' full factorial, and its precision splits into
    an auto-accepted figure and a combined one -- reported as two columns rather than
    collapsed into one, since collapsing would attribute the adjudicator's error rate to a
    threshold that never saw those pairs.
    """
    import pandas as pd

    rows = ["Matcher & Sev. & P & R & F1 \\\\\n\\hline\n"]
    free = pd.DataFrame(run["metrics"]["free_matchers"])
    for matcher in free["matcher"].unique():
        block = free[free["matcher"] == matcher]
        for severity, g in block.groupby("severity"):
            # threshold is None where no score met the Wilson-bound precision target on
            # dev -- nothing was accepted, which is a different statement from "accepted
            # everything and scored 0". Omitted from the table rather than shown as a
            # measured 0.000; the omission itself is reported in the caption below.
            if g["threshold"].isna().all():
                continue
            rows.append(
                f"{_esc(matcher)} & {severity} & {g['precision'].mean():.3f} & "
                f"{g['recall'].mean():.3f} & {g['f1'].mean():.3f} \\\\\n"
            )
    rows.append("\\hline\n")
    for row in run["metrics"]["cascade"]:
        auto = row.get("precision_auto_accepted")
        auto_s = "---" if auto is None else f"{auto:.3f}"
        rows.append(
            f"cascade & {row['severity']} & {row['precision']:.3f} ({auto_s} auto) & "
            f"{row['recall']:.3f} & {row['f1']:.3f} \\\\\n"
        )
    caption = (
        "Corpus A matcher comparison, precision/recall/F1 averaged over seeds (free "
        "matchers) or single-seed with every band pair adjudicated (cascade). Cascade "
        "precision is combined output; auto is the auto-accepted portion alone. Severity "
        "0.5 is an 800-pair stratified subsample, not the full band. Omitted rows have no "
        "threshold reaching the 0.95 precision floor on dev, not a measured zero."
    )
    return _wrap("".join(rows), caption, "tab:abtbuy", run["run_id"], "lcccc")


def table_classification(run: dict) -> str:
    """RQ2: both classical conditions at both levels, and the level's routed-to-review
    share broken out by cause.

    Class level restricts to labels meeting the training-example floor AND records
    genuinely carrying a class-level code -- a division-only code (``cpv.labelled_at``)
    is not a class and scoring it would credit the model for predicting that a buyer left
    the record unclassified. The two exclusions are reported apart because they are
    different failures: one is a rare category, the other is a category that does not
    exist for that record.
    """
    order = ["division", "class"]
    condition_label = {"tfidf_svm": "TF-IDF + SVM", "embedding_logreg": "Embedding + LogReg"}
    rows = ["Level & Condition & Macro F1 & Weighted F1 & Acc. & Rev. \\% \\\\\n\\hline\n"]
    for level in order:
        if level not in run["metrics"]["levels"]:
            continue
        result = run["metrics"]["levels"][level]
        routed = result["test_routed_to_review"]
        for name in ("tfidf_svm", "embedding_logreg"):
            if name not in result["conditions"]:
                continue
            c = result["conditions"][name]
            rows.append(
                f"{level.capitalize()} & {_esc(condition_label.get(name, name))} & "
                f"{c['macro_f1']:.3f} & {c['weighted_f1']:.3f} & {c['accuracy']:.3f} & "
                f"{100 * routed:.1f}\\% \\\\\n"
            )
    caption = (
        "Category assignment, both classical conditions. Class level restricts to "
        "labels meeting the training-example floor and records carrying a genuine "
        "class-level code; routed-to-review figures are broken out by cause in the text."
    )
    return _wrap(
        "".join(rows), caption, "tab:classification", run["run_id"], "llrrrr", compact=True
    )


def table_costs(run: dict) -> str:
    """T8_cost: cascade throughput and notional cost per 1,000 pairs, per severity.

    **Not yet registered in BUILDERS.** ``run_costs.py`` deduplicates the live ledger by
    ``prompt_sha256`` so this is already immune to replay inflation, but the band fraction
    and ``n_pairs`` it reads come from a ``run_dedup --cascade`` record that is not yet a
    finished 1,209/1,209 -- wire this in once that run lands, so the table reports the
    completed cascade rather than a partial day's.
    """
    m = run["metrics"]
    latency = "n/a" if m["mean_latency_ms"] is None else f"{m['mean_latency_ms']:.0f}"
    rows = [
        "Sev. & Band & Adjudicated/Pairs & USD/1000 adj. & Tokens/1000 adj. \\\\\n\\hline\n"
    ]
    for row in m["band"]:
        rows.append(
            f"{row['severity']} & {100 * row['band_fraction']:.1f}\\% & "
            f"{row['n_adjudicated']}/{row['n_pairs']} & "
            f"{row['usd_per_1000']:.4f} & {row['tokens_per_1000']:.0f} \\\\\n"
        )
    caption = (
        f"Cascade cost, deduplicated by prompt across every day the sweep took: "
        f"{m['n_calls']} distinct adjudications, mean latency {latency}\\,ms over live "
        f"calls only, throughput "
        f"{m['throughput_per_day']['calls_per_day']:.0f}/day bound by "
        f"{_esc(m['throughput_per_day']['binding_limit'])}. \\$0.00 actual spend; USD is "
        "notional at the ledger's rate card."
    )
    return _wrap("".join(rows), caption, "tab:costs", run["run_id"], "lrrrr", compact=True)


def table_transfer(run: dict) -> str:
    """External Validation: the cap-sweep attribution, per corpus per cap per severity.

    A reader cannot recover a 1,209x candidate-volume cost from reduction ratios sitting
    near 1 on either side, so candidates is reported directly rather than RR alone. This
    table answers "what does rescaling the guard cost", not "does the matcher rank the same
    way" -- that comparison lives in T4_abtbuy's Corpus A panel and T3_blocking's Corpus B
    panel, unaffected by any of this.
    """
    rows = ["Corpus & Sev. & Cap & PC & Candidates & Dropped \\\\\n\\hline\n"]
    for row in run["metrics"]["rows"]:
        short = "A (Abt-Buy)" if row["corpus"] == "corpus_a" else "B (Contracts Finder)"
        cap = "none" if row["cap"] is None else f"{row['cap']:,}"
        rows.append(
            f"{short} & {row['severity']} & {cap} & {row['pair_completeness']:.3f} & "
            f"{row['n_candidates']:,} & {row['blocks_dropped']:,} \\\\\n"
        )
    caption = (
        "Block-size cap sweep, both corpora, at severity 0.0 (Corpus B positives "
        "byte-identical there) and the rescaled cap at severity 0.25, where the two "
        "corpora's blocking behaviour diverges. PC is pair completeness; candidates and "
        "blocks dropped are reported directly since reduction ratio alone does not convey "
        "the volume cost of rescaling the cap."
    )
    return _wrap("".join(rows), caption, "tab:transfer", run["run_id"], "lcccrr", compact=True)


BUILDERS = {
    # T3_blocking dropped as a table (supervisor ruling: five tables not eleven); its
    # numbers that matter for prose are folded into T9_transfer or stated inline.
    "run_classify": {"T6_classification.tex": table_classification},
    "run_transfer_attribution": {"T9_transfer.tex": table_transfer},
    "run_costs": {"T8_cost.tex": table_costs},
    "run_dedup": {"T4_abtbuy.tex": table_abtbuy},
    "run_profile": {
        "T1_corpus.tex": table_corpus,
        # T1_discard, T1_leaf_sparsity, T1_label_support, T1_division_choice dropped as
        # tables (supervisor ruling): each is a single number or short list that reads
        # fine in a sentence. The builder functions stay, for anyone regenerating the
        # figure to check a prose number against.
    },
}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--runs", type=Path, default=RESULTS_ROOT)
    p.add_argument("--out", type=Path, default=TABLES_ROOT)
    p.add_argument(
        "--allow-dirty",
        action="store_true",
        help="build anyway; the resulting numbers are not reproducible and must not ship",
    )
    args = p.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)

    built, skipped = 0, []
    for script, tables in BUILDERS.items():
        try:
            run = load_run(latest_run(script, args.runs), root=args.runs)
        except FileNotFoundError:
            skipped.append(f"{script}: no run yet")
            continue

        try:
            _require_clean(run)
        except DirtyRun as e:
            if not args.allow_dirty:
                print(f"\nREFUSED: {e}\n", file=sys.stderr)
                return 2
            print(f"WARNING: {e}", file=sys.stderr)

        for filename, builder in tables.items():
            (args.out / filename).write_text(builder(run), encoding="utf-8")
            print(f"  {args.out / filename}  <- {run['run_id']}")
            built += 1

    for s in skipped:
        print(f"  skipped {s}", file=sys.stderr)
    print(f"built {built} tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
